### ISSUE TITLE
The class was not found in the chain configured namespaces

### ISSUE THREAD

**Issue by sweetguy0883** [doctrine/DoctrineCouchDBBundle#26]
Hello,
I am trying to use this bundle with Symfony2 version 2.2 system working for last few days but no luck. My database configuration is (I am using multiple databases) : 

<pre><code>
doctrine_couch_db:
  client:
    default_connection: default
    connections:
      default:
        dbname: test
      collections:
        dbname: database1
      signups:
        dbname: database2
      appdata:
        dbname: database3
  odm:
    default_document_manager: default
    document_managers:
      default:
        auto_mapping: true
</code></pre>

My document class is : 

<pre><code>
// MyApp\MyBundle\Document\Testing.php
namespace MyApp\MyBundle\Document;

use Doctrine\ODM\CouchDB\Mapping\Annotations as CouchDB;

/** @Document */
class Testing
{
    /** @Id */
    private $id;

    /** @Field(type="string") */
    private $name;
    
    /**
     * @param field_type $id
     */
    public function setId($id)
    {
        $this->name = $id;
    
        return $this;
    }
    
    /**
     * @return the $id 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param field_type $name
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * @return the $name 
     */
    public function getName()
    {
        return $this->name;
    }
}
</code></pre>

And my controller is : 

<pre><code>
// MyApp\MyBundle\Controller\TestController.php
namespace MyApp\MyBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class TestController extends Controller
{
    
    public function testAction()
    {
        $testing = new \MyApp\MyBundle\Document\Testing();
        $testing->setId("test2");
        $testing->setName("test name 2");
        $id = $testing->getId();
        $name = $testing->getName();
        
        $client = $this->container->get('doctrine_couch_db.client.default_connection');
        $dm = $this->container->get('doctrine_couch_db.odm.default_document_manager');
        $dm->persist($testing);
        $dm->flush();
        
        return array('id' => $id, 'name' => $name);
    }
}
</code></pre>

But my problem is, the code is working fine until I am using the <code>$dm->persist($testing);</code> function. But as soon as I am using it, the browser throws an error : 

<pre><code>
<h4> The class 'MyApp\MyBundle\Document\Testing' was not found in the chain configured namespaces</h4>
<h6>500 Internal Server Error - MappingException </h6>
</code></pre>

But if I am making the connection a way around (as described in <a href="http://docs.doctrine-project.org/projects/doctrine-couchdb/en/latest/reference/configuration.html#obtaining-the-documentmanager">Dortrine CouchDB Documentation</a>)

<pre><code>
$databaseName = "test";
$documentPaths = array("MyApp\MyBundle\Documents");
$httpClient = new \Doctrine\CouchDB\HTTP\SocketClient();
$dbClient = new \Doctrine\CouchDB\CouchDBClient($httpClient, $databaseName);

$config = new \Doctrine\ODM\CouchDB\Configuration();
$metadataDriver = $config->newDefaultAnnotationDriver($documentPaths);

$config->setProxyDir(__DIR__ . "/proxies");
$config->setMetadataDriverImpl($metadataDriver);
$config->setLuceneHandlerName('_fti');

$dm = new \Doctrine\ODM\CouchDB\DocumentManager($dbClient, $config);
</code></pre>

everything is running well. But I like the method described in this bundle as it looks neat and clean with less codes. Is there something I am missing or is it the problem with the 2.2 version. Please help.

**Comment by diderson** [comment]
@sweetguy0883 please adivises how solve it cause I have set 'auto_mapping: false' in a config but it still not working for me:
` $cat = $dm->getRepository("MyBundle\CouchDocument\PlaceCategory")->find($catId);`

the error: ` The class 'MyBundle\CouchDocument\PlaceCategory' was not found in the chain configured namespaces `

**Comment by stiffroy** [comment]
@diderson 
Make sure about a few things and please write it here.
1. Which package are you using (couchdb-odm or couchdb-odm-bundle)? They have different mapping instructions.
2. What about the folder structure and namespace?
3. Which editor are you using (with phpStorm or Net Beans you get a code correcting option)
4. How does the structure of the PlaceCategory class look like?
Regards....

**Comment by stiffroy** [comment]
@42aroger 
Sorry for my late reply. Could you solve your problem? I somehow overlooked your comment. Are you sure you are using monogodb-odm-bundle and not mongodb-odm? The stackoverflow code, it looks to be working.

**Comment by diderson** [comment]
@stiffroy I am using `couchdb-odm-bundle` but both are installed: `(couchdb-odm and couchdb-odm-bundle` actually I did manage to get this working by changing my config file to:
```annotation
doctrine_couch_db:
    client:
        dbname:               mccsa
        host:                 localhost
        port:                 5984
        user:                 null
        password:             null
        ip:                   null
        logging:              false

    odm:
        document_managers:
            default:
                mappings:
                    myBundle:
                        type: annotation
                auto_mapping: false
```
