### ISSUE TITLE
Problems with auto generated proxy classes [Bug?]

### ISSUE THREAD

**Issue by PATROMO** [doctrine/DoctrineCouchDBBundle#33]
<b>My Error</b>

<pre>
PHP Warning:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: require(D:/www/project/app/cache/dev/doctrine/CouchDBProxies\__CG__TestUserBundleCouchDocumentClient.php): failed to open stream: No such file or directory in D:\www\project\vendor\doctrine\couchdb-odm\lib\Doctrine\ODM\CouchDB\Proxy\ProxyFactory.php line 87' in D:\www\project\vendor\doctrine\couchdb-odm\lib\Doctrine\ODM\CouchDB\Proxy\ProxyFactory.php:87
Stack trace:
#0 D:\www\project\vendor\doctrine\couchdb-odm\lib\Doctrine\ODM\CouchDB\Proxy\ProxyFactory.php(87): Symfony\Component\Debug\ErrorHandler->handle(2, 'require(D:/www/...', 'D:\www\c...', 87, Array)
#1 D:\www\project\vendor\doctrine\couchdb-odm\lib\Doctrine\ODM\CouchDB\Proxy\ProxyFactory.php(87): Doctrine\ODM\CouchDB\Proxy\ProxyFactory::getProxy()
#2 D:\www\project\vendor\doctrine\couchdb-odm\lib\Doctrine\ODM\CouchDB\DocumentManager.php(302): Doctrine\ODM\CouchDB\Proxy\ProxyFactory->getProxy('Test in D:\www\project\vendor\doctrine\couchdb-odm\lib\Doctrine\ODM\CouchDB\Proxy\ProxyFactory.php on line 87

PHP Fatal error:  Doctrine\ODM\CouchDB\Proxy\ProxyFactory::getProxy(): Failed opening required 'D:/www/project/app/cache/dev/doctrine/CouchDBProxies\__CG__TestUserBundleCouchDocumentClient.php' (include_path='D:\www\project\vendor/phpunit/php-text-template;D:\www\project\vendor/phpunit/phpunit-mock-objects;D:\www\project\vendor/phpunit/php-file-iterator;D:\www\project\vendor/phpunit/php-code-coverage;D:\www\project\vendor/phpunit/php-token-stream;D:\www\project\vendor/phpunit/php-timer;D:\www\project\vendor/phpunit/phpunit;D:\www\project\vendor/symfony/yaml;.;C:\php\pear') in D:\www\project\vendor\doctrine\couchdb-odm\lib\Doctrine\ODM\CouchDB\Proxy\ProxyFactory.php on line 87
</pre>

<b>My config.yml</b>

<pre>
doctrine_couch_db:
    client:
        ....
    odm:
        auto_generate_proxy_classes: true
        auto_mapping: true
</pre>

<b>Quick and dirty solution:</b>
\vendor\doctrine\couchdb-odm\lib\Doctrine\ODM\CouchDB\Proxy\ProxyFactory.php:84 
if ($this->autoGenerate = true) {

**Comment by brunowego** [comment]
:+1:
