### ISSUE TITLE
'type': namespace collision with class properties

### ISSUE THREAD

**Issue by KampfCaspar** [doctrine/DoctrineCouchDBBundle#38]
Hi!

As it seems, a property named 'type' is used to save the respective couchdocument class name...

Unfortunately, 'type' is quite a common field name and therefore leads to conflicts. Wouldn't it be better to include the class name in doctrine_metadata?

KampfCaspar

**Comment by beberlei** [comment]
You can rename the type column using the mapping settings 'jsonName' or similar to 'mytype' in couch.
