### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by LikeBtn** [doctrine/DoctrineCouchDBBundle#45]
Hi

I have in my config.yml:

	doctrine_couch_db:
		client:
			default_connection:   connection1
			connections:
				connection1:
					host: "%doctrine_couch_db_host%"
					port: "%doctrine_couch_db_port%"
					dbname: "%doctrine_couch_db_dbname_1%"
					user: "%doctrine_couch_db_user%"
					password: "%doctrine_couch_db_password%"

				connection2:
					host: "%doctrine_couch_db_host%"
					port: "%doctrine_couch_db_port%"
					dbname: "%doctrine_couch_db_dbname_2%"
					user: "%doctrine_couch_db_user%"
					password: "%doctrine_couch_db_password%"
		odm:
			auto_mapping: true

But when I am trying to get document manager for connection2:

    $this->get('doctrine_couchdb.odm.connection2_document_manager');

I am getting the error:

    You have requested a non-existent service "doctrine_couchdb.odm.connection2_entity_manager".

**Comment by LikeBtn** [comment]
This way is not working too:
    $this->get('doctrine_couchdb')->getManager('connection2');

Error:
    Doctrine CouchDB Manager named "connection2" does not exist.

**Comment by LikeBtn** [comment]
Fixed by adding:

    odm:
        default_document_manager:  connection1
        document_managers:
            connection1:
                connection: connection1
            connection2:
                connection: connection2

But now I can't user auto_mapping: true

    You cannot enable "auto_mapping" when several CouchDB document managers are defined.

**Comment by stof** [comment]
the exception was expected: you were not defining multiple document managers in your initial config.

I'm closing this issue.
