### ISSUE TITLE
Installation Problems : Version Conflicts

### ISSUE THREAD

**Issue by The-Don-Himself** [doctrine/DoctrineCouchDBBundle#51]
Very Interested in testing out this bundle but cannot install it via composer getting the message that these conflict with your minimum requirements. Doing a bit of checking on Packagist could the following  be the reason. (I am trying to install the dev-master of all packages)

Bundle Requires

```
doctrine/couchdb-odm: @dev
doctrine/couchdb: @dev
```

But doctrine/couchdb-odm: @dev requires

```
doctrine/couchdb: ~1.0@beta
```

**Comment by funkytaco** [comment]
+1 I can't install via composer.

For an empty directory with no project:
>composer require doctrine/couchdb-odm-bundle

[InvalidArgumentException]                                                                                                                                   
  Could not find package doctrine/couchdb-odm-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  

======
Attempt #2 with an @dev flag

>composer require doctrine/couchdb-odm-bundle @dev

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/couchdb-odm-bundle v2.1-alpha1 requires doctrine/couchdb-odm @dev -> no matching package found.
    - doctrine/couchdb-odm-bundle dev-master requires doctrine/couchdb-odm @dev -> no matching package found.
    - doctrine/couchdb-odm-bundle dev-license requires doctrine/couchdb-odm >=2.0 -> no matching package found.
    - Installation request for doctrine/couchdb-odm-bundle @dev -> satisfiable by doctrine/couchdb-odm-bundle[dev-license, dev-master, v2.1-alpha1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by The-Don-Himself** [comment]
Any chance of a quick fix on this?
@beberlei

**Comment by The-Don-Himself** [comment]
I think changing composer minimum stability would solve this.
